/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package AppWithLogger;

import org.junit.Test;

import main.Application;

import static org.junit.Assert.*;

public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
        Application classUnderTest = new Application();
//        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
}
